INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (101, 'SNAP', 'APPROVED', 'VIKASH','$951');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (102, 'SNAP', 'DENIED', 'ANIL','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (103, 'SNAP', 'APPROVED', 'ANIKET','$751');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (104, 'SNAP', 'DENIED', 'VIVEK','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (105, 'SNAP', 'TERMINATED', 'ANJALI','NA');

INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (106, 'QHP', 'APPROVED', 'ABHISHEK','$401');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (107, 'QHP', 'DENIED', 'KALPNA','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (108, 'QHP', 'APPROVED', 'CHANDRESH','$711');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (109, 'QHP', 'DENIED', 'RAJESH','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (110, 'QHP', 'TERMINATED', 'PRAGATI','NA');

INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (111, 'CCAP', 'APPROVED', 'JYOTI','$521');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (112, 'CCAP', 'DENIED', 'MADAN','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (113, 'CCAP', 'APPROVED', 'NAVEEN','$311');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (114, 'CCAP', 'DENIED', 'NAVODITA','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (115, 'CCAP', 'TERMINATED', 'PRANJAL','NA');

INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (116, 'MEDICAID', 'APPROVED', 'PRIYANKA','$321');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (117, 'MEDICAID', 'DENIED', 'MOHAN','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (118, 'MEDICAID', 'APPROVED', 'VEDI','$631');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (119, 'MEDICAID', 'DENIED', 'RISHABH','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (120, 'MEDICAID', 'TERMINATED', 'SUPRIYA','NA');

INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (121, 'MEDICARE', 'APPROVED', 'REHANA','$421');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (122, 'MEDICARE', 'DENIED', 'SUGANDHA','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (123, 'MEDICARE', 'APPROVED', 'ASHOK','$631');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (124, 'MEDICARE', 'DENIED', 'ANNU','NA');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, PLAN_STATUS, HOLDER_NAME, BENEFIT_AMT) VALUES (125, 'MEDICARE', 'TERMINATED', 'PIYUSH','NA');



